/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InvoiceGenerator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Invoice;
import model.InvoiceItemsTable;
import model.InvoiceTable;
import model.Item;

/**
 *
 * @author osama ragheb
 */
public class InvoiceFrame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public InvoiceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newInvoiceDlg = new javax.swing.JDialog();
        customerName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        newInvoiceCustomerValue = new javax.swing.JTextField();
        newInvoiceDateValue = new javax.swing.JTextField();
        saveNewInvoice = new javax.swing.JButton();
        cancelNewInvoice = new javax.swing.JButton();
        newItemDlg1 = new javax.swing.JDialog();
        customerName1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        newItemNameValue = new javax.swing.JTextField();
        newItemPriceValue = new javax.swing.JTextField();
        saveNewItem = new javax.swing.JButton();
        cancelNewItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newItemCountValue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.getSelectionModel().addListSelectionListener(invoiceGenerator);
        newInvioce = new javax.swing.JButton();
        deleteInviove = new javax.swing.JButton();
        newItem = new javax.swing.JButton();
        deleteItem = new javax.swing.JButton();
        invoiceNo = new javax.swing.JLabel();
        invoiceDate = new javax.swing.JLabel();
        invoiceCustomer = new javax.swing.JLabel();
        invoiceTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        invoiceNumberL = new javax.swing.JLabel();
        invoiceDateL = new javax.swing.JLabel();
        customerNoL = new javax.swing.JLabel();
        invoiceTotalL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        invoiceDateValue = new javax.swing.JLabel();
        invoiceCustomerValue = new javax.swing.JLabel();
        invoiceTotalValue = new javax.swing.JLabel();
        invoiceNoValue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        SaveFile = new javax.swing.JMenuItem();

        newInvoiceDlg.setTitle("Create NewI nvoice");
        newInvoiceDlg.setSize(new java.awt.Dimension(350, 250));

        customerName.setText("Customer Name");

        date.setText("Invoice Date");

        newInvoiceDateValue.setToolTipText("");

        saveNewInvoice.setText("Save");
        saveNewInvoice.setToolTipText("");
        saveNewInvoice.setActionCommand("Save New Invoice");
        saveNewInvoice.addActionListener(invoiceGenerator);

        cancelNewInvoice.setText("Cancel");
        cancelNewInvoice.setToolTipText("");
        cancelNewInvoice.setActionCommand("Cancel New Invoice");
        cancelNewInvoice.addActionListener(invoiceGenerator);

        javax.swing.GroupLayout newInvoiceDlgLayout = new javax.swing.GroupLayout(newInvoiceDlg.getContentPane());
        newInvoiceDlg.getContentPane().setLayout(newInvoiceDlgLayout);
        newInvoiceDlgLayout.setHorizontalGroup(
            newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceDlgLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveNewInvoice)
                    .addComponent(date)
                    .addComponent(customerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoiceDlgLayout.createSequentialGroup()
                        .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newInvoiceDateValue, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(newInvoiceCustomerValue))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoiceDlgLayout.createSequentialGroup()
                        .addComponent(cancelNewInvoice)
                        .addGap(66, 66, 66))))
        );
        newInvoiceDlgLayout.setVerticalGroup(
            newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceDlgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName)
                    .addComponent(newInvoiceCustomerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(newInvoiceDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(newInvoiceDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewInvoice)
                    .addComponent(cancelNewInvoice))
                .addGap(21, 21, 21))
        );

        newInvoiceDlg.getAccessibleContext().setAccessibleDescription("");
        newInvoiceDlg.getAccessibleContext().setAccessibleParent(null);

        newItemDlg1.setTitle("Create New Item");
        newItemDlg1.setSize(new java.awt.Dimension(350, 250));

        customerName1.setText("Item Name");

        date1.setText("Item Price");

        newItemPriceValue.setToolTipText("");

        saveNewItem.setText("Save");
        saveNewItem.setToolTipText("");
        saveNewItem.setActionCommand("Save New Item");
        saveNewItem.addActionListener(invoiceGenerator);

        cancelNewItem.setText("Cancel");
        cancelNewItem.setToolTipText("");
        cancelNewItem.setActionCommand("Cancel New Item");
        cancelNewItem.addActionListener(invoiceGenerator);

        jLabel2.setText("Item Count");

        javax.swing.GroupLayout newItemDlg1Layout = new javax.swing.GroupLayout(newItemDlg1.getContentPane());
        newItemDlg1.getContentPane().setLayout(newItemDlg1Layout);
        newItemDlg1Layout.setHorizontalGroup(
            newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newItemDlg1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveNewItem)
                    .addComponent(date1)
                    .addComponent(customerName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newItemDlg1Layout.createSequentialGroup()
                        .addComponent(cancelNewItem)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newItemDlg1Layout.createSequentialGroup()
                        .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newItemCountValue)
                            .addComponent(newItemPriceValue, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(newItemNameValue))
                        .addGap(42, 42, 42))))
        );
        newItemDlg1Layout.setVerticalGroup(
            newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newItemDlg1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName1)
                    .addComponent(newItemNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(newItemPriceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newItemCountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(newItemDlg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewItem)
                    .addComponent(cancelNewItem))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        newInvioce.setText("New Invioce");
        newInvioce.setActionCommand("Create New Invoice");
        newInvioce.addActionListener(invoiceGenerator);
        newInvioce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInvioceActionPerformed(evt);
            }
        });

        deleteInviove.setText("Delete Invoice");
        deleteInviove.addActionListener(invoiceGenerator);

        newItem.setText("New Item");
        newItem.setActionCommand("Create New Item");
        newItem.addActionListener(invoiceGenerator);

        deleteItem.setText("Delete");
        deleteItem.setActionCommand("Delete Item");
        deleteItem.addActionListener(invoiceGenerator);

        invoiceNo.setText("Invioce Number");

        invoiceDate.setText("Invoice Date");
        invoiceDate.setToolTipText("");

        invoiceCustomer.setText("Customer Name");

        invoiceTotal.setText("Invoice Total");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Invoice Table");
        jLabel5.setToolTipText("");

        jLabel6.setText("Invoice Items");
        jLabel6.setToolTipText("");

        jMenu1.setText("File");

        loadFile.setText("Load File");
        loadFile.setToolTipText("");
        loadFile.addActionListener(invoiceGenerator);
        jMenu1.add(loadFile);

        SaveFile.setText("Save File");
        SaveFile.addActionListener(invoiceGenerator);
        jMenu1.add(SaveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invoiceTotalL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customerNoL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invoiceDateL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceNo)
                                .addGap(35, 35, 35)
                                .addComponent(invoiceNumberL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoiceCustomerValue)
                            .addComponent(invoiceTotalValue)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invoiceNoValue)
                                    .addComponent(invoiceDateValue)))))
                    .addComponent(jLabel6))
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(newInvioce)
                .addGap(51, 51, 51)
                .addComponent(deleteInviove)
                .addGap(123, 123, 123)
                .addComponent(newItem)
                .addGap(68, 68, 68)
                .addComponent(deleteItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceNo)
                            .addComponent(invoiceNumberL)
                            .addComponent(jLabel1)
                            .addComponent(invoiceNoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDate)
                            .addComponent(invoiceDateL)
                            .addComponent(invoiceDateValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceCustomer)
                            .addComponent(customerNoL)
                            .addComponent(invoiceCustomerValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceTotal)
                            .addComponent(invoiceTotalL)
                            .addComponent(invoiceTotalValue))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteInviove)
                    .addComponent(newInvioce)
                    .addComponent(newItem)
                    .addComponent(deleteItem))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newInvioceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInvioceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newInvioceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JButton cancelNewInvoice;
    private javax.swing.JButton cancelNewItem;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerName1;
    private javax.swing.JLabel customerNoL;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JButton deleteInviove;
    private javax.swing.JButton deleteItem;
    private javax.swing.JLabel invoiceCustomer;
    private javax.swing.JLabel invoiceCustomerValue;
    private javax.swing.JLabel invoiceDate;
    private javax.swing.JLabel invoiceDateL;
    private javax.swing.JLabel invoiceDateValue;
    private javax.swing.JLabel invoiceNo;
    private javax.swing.JLabel invoiceNoValue;
    private javax.swing.JLabel invoiceNumberL;
    private javax.swing.JLabel invoiceTotal;
    private javax.swing.JLabel invoiceTotalL;
    private javax.swing.JLabel invoiceTotalValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JButton newInvioce;
    private javax.swing.JTextField newInvoiceCustomerValue;
    private javax.swing.JTextField newInvoiceDateValue;
    private javax.swing.JDialog newInvoiceDlg;
    private javax.swing.JButton newItem;
    private javax.swing.JTextField newItemCountValue;
    private javax.swing.JDialog newItemDlg1;
    private javax.swing.JTextField newItemNameValue;
    private javax.swing.JTextField newItemPriceValue;
    private javax.swing.JButton saveNewInvoice;
    private javax.swing.JButton saveNewItem;
    // End of variables declaration//GEN-END:variables
private InvoiceGenerator invoiceGenerator = new InvoiceGenerator(this);
private List<Invoice> invoiceList;
private InvoiceTable invoiceTable;
private InvoiceItemsTable itemsTable;
private List<Item> itemList;

    public List<Invoice> getInvoiceList() {
        return invoiceList;
    }

    public void setInvoiceList(List<Invoice> invoiceList) {
        this.invoiceList = invoiceList;
    }

    public InvoiceTable getInvoiceTable() {
        return invoiceTable;
    }

    public void setInvoiceTable(InvoiceTable invoiceTable) {
        this.invoiceTable = invoiceTable;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JMenuItem getSave() {
        return SaveFile;
    }

    public void setSave(JMenuItem save) {
        this.SaveFile = save;
    }

    public InvoiceItemsTable getItemsTable() {
        return itemsTable;
    }

    public void setItemsTable(InvoiceItemsTable itemsTable) {
        this.itemsTable = itemsTable;
    }

    public List<Item> getItemList() {
        return itemList;
    }

    public void setItemList(List<Item> itemList) {
        this.itemList = itemList;
    }

   
    public JLabel getInvoiceCustomerValue() {
        return invoiceCustomerValue;
    }

    public void setInvoiceCustomerValue(JLabel invoiceCustomerValue) {
        this.invoiceCustomerValue = invoiceCustomerValue;
    }

    public JLabel getInvoiceDateValue() {
        return invoiceDateValue;
    }

    public void setInvoiceDateValue(JLabel invoiceDateValue) {
        this.invoiceDateValue = invoiceDateValue;
    }

    public JLabel getInvoiceNoValue() {
        return invoiceNoValue;
    }

    public void setInvoiceNoValue(JLabel invoiceNoValue) {
        this.invoiceNoValue = invoiceNoValue;
    }

    public JLabel getInvoiceTotalValue() {
        return invoiceTotalValue;
    }

    public void setInvoiceTotalValue(JLabel invoiceTotalValue) {
        this.invoiceTotalValue = invoiceTotalValue;
    }

    public JTextField getNewInvoiceCustomerValue() {
        return newInvoiceCustomerValue;
    }

    public void setNewInvoiceCustomerValue(JTextField newInvoiceCustomerValue) {
        this.newInvoiceCustomerValue = newInvoiceCustomerValue;
    }

    public JTextField getNewInvoiceDateValue() {
        return newInvoiceDateValue;
    }

    public void setNewInvoiceDateValue(JTextField newInvoiceDateValue) {
        this.newInvoiceDateValue = newInvoiceDateValue;
    }

    public JDialog getNewInvoiceDlg() {
        return newInvoiceDlg;
    }

    public void setNewInvoiceDlg(JDialog newInvoiceDlg) {
        this.newInvoiceDlg = newInvoiceDlg;
    }

    public JTextField getNewItemCountValue() {
        return newItemCountValue;
    }

    public void setNewItemCountValue(JTextField newItemCountValue) {
        this.newItemCountValue = newItemCountValue;
    }

    public JDialog getNewItemDlg1() {
        return newItemDlg1;
    }

    public void setNewItemDlg1(JDialog newItemDlg1) {
        this.newItemDlg1 = newItemDlg1;
    }

    public JTextField getNewItemNameValue() {
        return newItemNameValue;
    }

    public void setNewItemNameValue(JTextField newItemNameValue) {
        this.newItemNameValue = newItemNameValue;
    }

    public JTextField getNewItemPriceValue() {
        return newItemPriceValue;
    }

    public void setNewItemPriceValue(JTextField newItemPriceValue) {
        this.newItemPriceValue = newItemPriceValue;
    }


}
